num_quark 3
alttc 0.1053
Nt 72
Nx 24
N_start 10000
Ncnfg 100 
gap 50 
t_sep_start 8
t_sep_end 8
t_sep_gap 8
ENV_start 5
ENV_end 100
ENV_gap 5
Pz_start 0
Pz_end 0
Py_start 0
Py_end 0
Px_start 0
Px_end 0
first_quark_3pt_corr_path /public/home/sush/3pt_distillation/proton/result/24x72/Px%dPy%dPz%d/ENV_%d_%dx%d/corr_uuu_conf%d_gamma4_3pt_tseq%d_U.dat
second_quark_3pt_corr_path /public/home/sush/3pt_distillation/proton/result/24x72/Px%dPy%dPz%d/ENV_%d_%dx%d/corr_uuu_conf%d_gamma4_3pt_tseq%d_D.dat
corr_2pt_path /public/home/sush/3pt_distillation/proton/result/24x72/Px%dPy%dPz%d/ENV_%d_%dx%d/corr_uuu_conf%d_2pt.dat
C2pt_type log
save_path ./proton/