num_quark 2
alttc 0.1057
Nt 72
Nx 24
Ncnfg 15 
gap 50 
N_start 10150
t_sep 32 
ENV_start 1
ENV_end 99
ENV_gap 2
Pz_start 0
Pz_end 0
Py_start 0
Py_end 0
Px_start 0
Px_end 0
first_quark_3pt_corr_path /public/home/sush/3pt_test/pion/result/ENV_%d_%dx%d/corr_uud_plus_Px%dPy%dPz%d_conf%d_gamma4_3pt_tseq32_U.dat
second_quark_3pt_corr_path /public/home/sush/3pt_test/proton/result/3pt_2pt/ENV_%d_%dx%d/corr_uud_plus_Px%dPy%dPz%d_conf%d_gamma4_3pt_tseq8_D_cupy.dat
corr_2pt_path /public/home/sush/3pt_test/pion/result/ENV_%d_%dx%d/corr_uud_plus_Px%dPy%dPz%d_conf%d_2pt.dat
save_path ./pion/